adaptive_ratio: 4
cutoffs:
- 5000
- 25000
- 50000
dropout: 0.1
eval_batch: 1
eval_chunk: 4096
hebbian: true
hebbian_T: 500
hebbian_gamma: 0.01
lr: 0.0005
model: /data/scratch/zxyan/micronet/model.py
model_class: Transformer
n_embed: 256
n_head: 8
n_inner: 1024
n_k: 32
n_layers: 16
n_seq: 64
n_v: 32
n_vocab: 267735
opt_level: O0
pos_emb: trained
scheduler: cosine
step_eval: 500
step_save: 5000
step_warmup: 100
train_batch: 17
train_chunk: 1088
